import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, ShieldAlert } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 font-sans p-4 md:p-8 lg:p-16">
      <div className="max-w-4xl mx-auto bg-white p-8 lg:p-12 rounded-3xl shadow-sm border border-gray-100">
        <Link
          to="/home"
          className="inline-flex items-center gap-2 text-indigo-600 hover:text-indigo-800 transition-colors mb-10"
        >
          <ArrowLeft size={20} />
          <span className="font-semibold uppercase tracking-wide text-sm">
            Return to Platform
          </span>
        </Link>

        <div className="flex items-center gap-4 mb-10">
          <div className="p-3 bg-orange-100 text-orange-600 rounded-xl">
            <ShieldAlert size={32} />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-gray-900">
            Disclaimer
          </h1>
        </div>

        <div className="prose prose-lg text-gray-600 max-w-none space-y-8">
          <p>
            Last Updated: <strong>May 2024</strong>
          </p>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              1. General Information
            </h2>
            <p>
              The information provided by NEXA POS ("we," "us," or "our") on the{" "}
              <strong>NEXA POS System</strong> website and application is for
              general informational and operational purposes only. All
              information on the site and our{" "}
              <strong>POS System in Pakistan</strong> is provided in good faith.
              We make no representation or warranty of any kind, express or
              implied, regarding the absolute uninterrupted uptime, accuracy,
              validity, reliability, availability, or completeness of any
              information or data processed by our{" "}
              <strong>Retail POS Software</strong> or{" "}
              <strong>Inventory Management Software</strong>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              2. Professional Non-Liability
            </h2>
            <p>
              Under no circumstance shall we have any liability to you for any
              loss, financial damage, ledger discrepancies, or inventory
              miscalculations incurred as a result of the use of our{" "}
              <strong>Billing Software</strong> or reliance on any information
              provided on the <strong>Shop Management System</strong>. Your use
              of the application and your reliance on any financial calculations
              generated by our platform is solely at your own risk. Businesses
              are advised to maintain secondary accounting standards. While NEXA
              POS implements robust offline-caching and Supabase cloud
              persistence to prevent data loss, network anomalies or
              misconfiguration by administrative users can result in
              discrepancies.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              3. External Links Disclaimer
            </h2>
            <p>
              The <strong>POS System in Pakistan</strong> platform may contain
              links to outside websites or third-party APIs (such as payment
              gateways, SMS gateways). Such external relationships are not
              investigated, monitored, or checked for accuracy by us. We do not
              warrant, endorse, guarantee, or assume responsibility for the
              accuracy or reliability of any information offered by third-party
              websites linked through our{" "}
              <strong>Shop Management System</strong>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              4. Software Usage & Hardware Compatibility
            </h2>
            <p>
              NEXA POS is distributed as a Progressive Web Application.
              Compatibility with specific hardware—including but not limited to
              thermal receipt printers, USB peripherals, and mechanical POS cash
              drawers—is highly dependent on your operating system’s browser
              integrations. We do not explicitly guarantee universal
              compatibility with all legacy hardware systems when utilizing this{" "}
              <strong>Retail POS Software</strong>.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">
              5. Tax & Legal Compliance
            </h2>
            <p>
              NEXA POS provides digital ledgers, receipt generation, and profit
              tracking analytical modules. However, the{" "}
              <strong>Billing Software</strong> does not act as a substitute for
              a certified public accountant or legal tax advisor. Generating
              invoices via our <strong>Inventory Management Software</strong>{" "}
              system implies you take full responsibility for ensuring your
              local tax authority requirements (such as FBR in Pakistan) are
              thoroughly met.
            </p>
          </section>

          <hr className="my-10 border-gray-200" />
          <p className="text-sm text-gray-500 italic">
            By using our software, you hereby consent to our disclaimer and
            agree to its terms. If you require any more information or have any
            questions about our site's disclaimer, please feel free to contact
            us via the contact page.
          </p>
        </div>
      </div>
    </div>
  );
}
